name: Run Robot Tests & Flask Dashboard

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Allow manual triggering

jobs:
  run-tests-and-dashboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework Tests
        run: |
          python3 -m robot.run --outputdir . --report report.html --log log.html Web

      - name: Check if output.xml exists
        run: |
          if [ ! -f output.xml ]; then
            echo "File output.xml not found!"
            exit 1
          fi

      - name: Save output.xml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: output.xml

      - name: Run Flask Dashboard in Background
        run: |
          nohup python app.py > flask.log 2>&1 &
          sleep 5  # wait for the server to be ready

      - name: Print status
        run: |
          echo "Robot test completed and Flask dashboard is running."
          echo "Access local dashboard: http://localhost:5000"
          cat flask.log

